### ISSUE TITLE
No Y axis movements

### ISSUE THREAD

**Issue by AaronYang-Orange** [KevinLTT/video2bvh#10]
Thanks Kevin for your fantastic work!

I came across an issue when I was analysing videos. When people walk towards to the camera, the   3d coordinates on y axis are not changed or changed slightly. Could I ask is there any settings to upgrade the performance?

I use Openpose with max accuracy settings to generate 2d data and the VideoPose3D pre-trained model to convert to 3d. The video is very simple, just a person walks towards to the camera with the distance around 7 meters.

Thanks again!

Looking forward to hearing from you!

Aaron

**Comment by KevinLTT** [comment]
Hi, Aaron,

The estimated 3D joint positions are relative to root joint(hip), so global translation is not supported. 
There are some works focus on absolute human pose estimation, such as [Absolute Human Pose Estimation with Depth Prediction Network](https://arxiv.org/pdf/1904.05947.pdf), you can refer to this paper for more information.

**Comment by AaronYang-Orange** [comment]
Thanks Kevin for your reply and suggestion!

OK, I understand. That could be very useful.

Thanks again for your work and sharing this project!

Regards,

Aaron
