### ISSUE TITLE
关键点问题

### ISSUE THREAD

**Issue by xinzi2018** [KevinLTT/video2bvh#11]
您在文档写的是使用的openpose来检测25个关键点，但在骨骼中观察是17个关键点？

**Comment by KevinLTT** [comment]
是的, 输入的二维关节点数目是25, 输出的三维关节点数目是17

**Comment by xinzi2018** [comment]
我们目前的工作是没法转成25个三维关键点（bvh）吗？ 我看openpose官方文档也没有给出相应的json文件转bvh格式

**Comment by KevinLTT** [comment]
我们模型在训练的时候使用的三维姿态是17个关节点的, 所以模型输出是固定17个节点的. 你需要其他关节点的位置的话可以通过插值或者重新训练三维姿态估计估计模型, human3.6m数据集的原始三维姿态是包括32个关节点的.
