### ISSUE TITLE
 About direction vector 

### ISSUE THREAD

**Issue by hanhailangya** [KevinLTT/video2bvh#14]
老师您好，在您的代码中有一点不太理解的是：为什么在计算肩膀Shoulder、肘部Elbow的时候要采用xy方向向量计算方向余弦矩阵呢？按照初始姿态定义的情况，此时可以确定平面的还是xz两个方向向量啊，LeftWrist—>LeftElbow这个向量按初始姿态应该算不出y分量的值呀，同样的疑惑还有Neck选取的yz向量，我按照我的想法修改了但是结果不正确，可能理解有误，但不知道其中问题出在哪，还望老师解答。
            elif joint == 'Neck':
                x_dir = None
                y_dir = pose[index['Thorax']] - pose[joint_idx]
                z_dir = pose[index['HeadEndSite']] - pose[index['Thorax']]
                order = 'zxy'
            elif joint == 'LeftShoulder':
                x_dir = pose[index['LeftElbow']] - pose[joint_idx]
                y_dir = pose[index['LeftElbow']] - pose[index['LeftWrist']]
                z_dir = None
                order = 'xzy'
![image](https://user-images.githubusercontent.com/37034839/86322723-113f3180-bc6e-11ea-869c-9c116e19543b.png)

**Comment by KevinLTT** [comment]
老师不敢当😂 这段时间比较忙没有及时回复
你的理解没有错, 以shoulder为例, 用于确定shoulder姿态的是xz两个方向向量
你可以看下dcm_from_axis的代码, 实际上xzy顺序里面, 首先确定的是x轴, 即leftElobow->leftShoulder
然后确定的是z轴, 它是通过x轴和给定的y方向叉乘出来的, 最后再通过x轴和z轴叉乘得到的y轴
neck也是同理, 先确定的是z轴, 再通过叉乘得出x轴, 最后求出y轴
https://github.com/KevinLTT/video2bvh/blob/87f61358c26bd395bf7311765a0f2d11f4d0a56f/bvh_skeleton/math3d.py#L14-L33

**Comment by wtnan2003** [comment]
@KevinLTT 
在读代码时候遇到困惑，在算旋转矩阵时候
https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/math3d.py#L23-L30
为什么是通过自身叉乘计算呢，旋转矩阵通过前后向量的旋转角度的来计算，而此处似乎没有与上一帧的向量进行计算，而且此处定义的x_dir 和y_dir 似乎并不正交阿https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/cmu_skeleton.py#L237-L241

2.为何计算欧拉角要将旋转矩阵转为四元数为中介，似乎旋转矩阵有直接计算欧拉角的方法

3D数学基础浅薄，有谬误望谅解，若能解答很感激

**Comment by birdflies** [comment]
> @KevinLTT
> 在读代码时候遇到困惑，在算旋转矩阵时候
> https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/math3d.py#L23-L30
> 
> 
> 为什么是通过自身叉乘计算呢，旋转矩阵通过前后向量的旋转角度的来计算，而此处似乎没有与上一帧的向量进行计算，而且此处定义的x_dir 和y_dir 似乎并不正交阿
> https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/cmu_skeleton.py#L237-L241
> 
> 2.为何计算欧拉角要将旋转矩阵转为四元数为中介，似乎旋转矩阵有直接计算欧拉角的方法
> 
> 3D数学基础浅薄，有谬误望谅解，若能解答很感激

请问这个您弄明白了没？～

**Comment by birdflies** [comment]
> @KevinLTT
> 在读代码时候遇到困惑，在算旋转矩阵时候
> https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/math3d.py#L23-L30
> 
> 
> 为什么是通过自身叉乘计算呢，旋转矩阵通过前后向量的旋转角度的来计算，而此处似乎没有与上一帧的向量进行计算，而且此处定义的x_dir 和y_dir 似乎并不正交阿
> https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/cmu_skeleton.py#L237-L241
> 
> 2.为何计算欧拉角要将旋转矩阵转为四元数为中介，似乎旋转矩阵有直接计算欧拉角的方法
> 
> 3D数学基础浅薄，有谬误望谅解，若能解答很感激

请问这个您弄明白没？

**Comment by ZaVang** [comment]
> > @KevinLTT
> > 在读代码时候遇到困惑，在算旋转矩阵时候
> > https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/math3d.py#L23-L30
> > 
> > 为什么是通过自身叉乘计算呢，旋转矩阵通过前后向量的旋转角度的来计算，而此处似乎没有与上一帧的向量进行计算，而且此处定义的x_dir 和y_dir 似乎并不正交阿
> > https://github.com/KevinLTT/video2bvh/blob/312d18f53bf31c37adcaf07c97098b67dbf9804a/bvh_skeleton/cmu_skeleton.py#L237-L241
> > 
> > 2.为何计算欧拉角要将旋转矩阵转为四元数为中介，似乎旋转矩阵有直接计算欧拉角的方法
> > 3D数学基础浅薄，有谬误望谅解，若能解答很感激
> 
> 请问这个您弄明白没？

第一个不需要正交，只需要这俩向量确定的平面就行，你看上面作者回复的具体原理。第二个的话我个人猜测是因为这样比较方便吧。图形学中在计算时候四元数用的比较多，因为他进行各种复合计算包括插值等会非常方便。源代码中需要用四元数来计算局部的旋转，用四元数还可以避免万向锁的问题，所以只在最后才转换为欧拉角。而且从旋转矩阵到欧拉角的转换会非常麻烦，应该要对不同的情况进行分类讨论。
