### ISSUE TITLE
can i convert 3d coordinates to bvh file?

### ISSUE THREAD

**Issue by supernova817** [KevinLTT/video2bvh#15]
I have 3D coordinate data (.h5 file)
I want to convert the data of these coordinates into a bvh file.
What should I do?

**Comment by supernova817** [comment]
h5 file has Frame1(X1, Y1, Z1, X2, Y2, Z2, ... Xn, Yn, Xn)
                ......
                FrameW(X1, Y1, Z1, X2, Y2, Z2, ... Xn, Yn, Xn)

**Comment by KevinLTT** [comment]
Yes, just replace 3D joints estimation result with your own data and the following porcesses are the same.
Ensure that the joint order is compatibale with the skeleton definition.

**Comment by supernova817** [comment]
It has finger 3d joint 
Can I convert it too?

**Comment by KevinLTT** [comment]
Finger joint is not included. You can write your own skeleton module to implement it.

**Comment by wangmiaowei** [comment]
@supernova817  Did you convert the finger 3d joint to .bvh file successful? can you give me a suggest?
