### ISSUE TITLE
why order is xzy? 

### ISSUE THREAD

**Issue by guker** [KevinLTT/video2bvh#17]
https://github.com/KevinLTT/video2bvh/blob/87f61358c26bd395bf7311765a0f2d11f4d0a56f/bvh_skeleton/h36m_skeleton.py#L212

why order is xzy,  what is difference between xzy and zyx?

**Comment by KevinLTT** [comment]
See definition of `dcm_from_axis` below. 'xzy' means firstly choose `x_dir` as x-axis, and then use cross product of `x_dir` and `y_dir` to find z-axis, and finally get y-axis by cross product of x-axis and z-axis.
https://github.com/KevinLTT/video2bvh/blob/87f61358c26bd395bf7311765a0f2d11f4d0a56f/bvh_skeleton/math3d.py#L14-L33

**Comment by Kismetzc** [comment]
Hi,@guker and @KevinLTT 
I still don't quite understand, can you please explain in more detail
