### ISSUE TITLE
how to change bvh picture size

### ISSUE THREAD

**Issue by shichaog** [KevinLTT/video2bvh#18]
非常好的工程，感谢，我这边有个问题，导出的bvh用blender2.8导入之后，尺寸太大不合适，请问哪里可以设置bvh大小呢？非常感谢！

**Comment by KevinLTT** [comment]
你可以将3维姿态的坐标做相应的缩放, 或者直接修改bvh文件里头几行骨架定义中的offset尺寸.

**Comment by shichaog** [comment]
@KevinLTT 是的，谢谢
