### ISSUE TITLE
3D Joints data format

### ISSUE THREAD

**Issue by ujjawalcse** [KevinLTT/video2bvh#19]
Hey @KevinLTT,
Pleased to see this amazing work.
I need a help from you.
Actually I wanna utilize your code just to convert 3d joints data to .bvh file.
Can I know your exact format of 3d joints data (3d_pose.npy) so that I can convert my data into this format?
Or can you please provide '3d_pose.npy' file for a sample if possible as soon as possible?

**Comment by KevinLTT** [comment]
You can  refer this sample https://github.com/KevinLTT/video2bvh/blob/master/miscs/cxk_cache/3d_pose.npy.
The skeleton is defined in https://github.com/KevinLTT/video2bvh/blob/master/bvh_skeleton/cmu_skeleton.py.
