### ISSUE TITLE
share one keypoints_list file？or all the 2d，3d keypoint file of you demo.

### ISSUE THREAD

**Issue by Ai-is-light** [KevinLTT/video2bvh#2]
I'm really insterested in your excellent repo. However, I can not success in deploying one openpose's repo environment, owing to the special service environment of my using. So, I try to use other keypoint detection network for producing the keypoint. I hope you can support some middle file of 2d,3d keypoint.
Thx
Looking forward to any replies

**Comment by KevinLTT** [comment]
I have uploaded the 2D pose, 3D pose and bvh results of the demo video. See https://github.com/KevinLTT/video2bvh/tree/master/miscs/cxk_cache . I hope this help you.

**Comment by Ai-is-light** [comment]
thx
