### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Sinnaj94** [KevinLTT/video2bvh#21]
Hey! I would like to use this repository for educational purposes. Is that possible? Could you add a license to the repository to clarify that? Thanks in advance.

**Comment by KevinLTT** [comment]
Yes, I'm pleased that this project can help you.
I will add a license later.

**Comment by Sinnaj94** [comment]
Hey @KevinLTT, sorry to bother you again. Can you add the License soon? That would be really great!

**Comment by KevinLTT** [comment]
The license has been added.

**Comment by Sinnaj94** [comment]
Thanks a lot!
