### ISSUE TITLE
Is it possible to add face and hand keypoints?

### ISSUE THREAD

**Issue by JunFang-NWPU** [KevinLTT/video2bvh#23]
Hi,

Thanks for the great work for retargeting. In addition to pose keypoints, is it possible to add face and hand keypoints?

Thanks.

**Comment by KevinLTT** [comment]
OpenPose supports 2D face and hand keypoint detection.
3D pose estimation of face and hand is not supported in this project.

**Comment by JunFang-NWPU** [comment]
Maybe 3d pose and retargeting of face and hand can be supported in the future in this project.
