### ISSUE TITLE
It seems that the openpose_skeleton.py isn't finished yet?

### ISSUE THREAD

**Issue by zhangzhensong** [KevinLTT/video2bvh#25]
Hi, it the cmu_skeleton.py you have also implemented get_bvh_header and pose2euler, while in openpose_skeleton.py not. Do you have plan to develop these functions for openpose skeleton?

**Comment by KevinLTT** [comment]
I implemented the CMU one because the skeleton provided by MakeHuman is in CMU format.
Currently I ~~am lazy~~ have no time to implement the openpose methods.
You can implemented it if you have interests, and PR is welcome~
