### ISSUE TITLE
finger bvh

### ISSUE THREAD

**Issue by wangmiaowei** [KevinLTT/video2bvh#26]
Can you give me some advice about converting finger 3D coordinate to .bvh file.

**Comment by KevinLTT** [comment]
I haven't implemented finger joint angle calculation, but I think it can be decomposed to these steps
1) solve the palm plane with metacarpophalangeal joints (solve plane with 4 points)
2) calculate the strech and bend angle of proximal interphalangeal joints (angles between vector and plane)
3) calculat the bend angle of the distal interphalangeal joints and finger tip joint (angle between vectors)
