### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by serviceberry3** [KevinLTT/video2bvh#27]
Hi, 

Do you know offhand which of 3d-pose-baseline or VideoPose3D is faster/lighter? I'm looking to do 2d->3d pose inference on an Android device in real time. I tried VideoPose3D but it was way too slow...am wondering if I should also try 3d-pose-baseline.

**Comment by KevinLTT** [comment]
3d-pose-baseline is more lightweight because it only uses single frame and its network is FC based.
I think if the accuracy is not that critical, you can try 3d-pose-baseline.
