### ISSUE TITLE
将生成的bvh导入3dsmax

### ISSUE THREAD

**Issue by wtnan2003** [KevinLTT/video2bvh#4]
生成的bvh 是CMU骨骼 和3dsmax 不匹配，我将其重命名后尝试导入3dsmax bip骨骼，在bvhacker上观察骨骼是正常的
![](https://user-images.githubusercontent.com/20351890/71143315-151ce080-2255-11ea-832e-1c6fc76762c7.png)
但是导入到3dsmax中，骨骼就挤在一起
![](https://user-images.githubusercontent.com/20351890/71143417-7775e100-2255-11ea-8aec-15420a35f551.png)

通过尝试，发现跟 initial_directions有关
https://github.com/KevinLTT/video2bvh/blob/3948283164cbc190ae8cfca1abb054cd058b230e/bvh_skeleton/cmu_skeleton.py#L88

当我更改了initial_directions，将里面各项顺序改成[y,z,x],即：
```
for key,item in initial_directions.items():
    initial_directions[key] = [item[1],item[2],item[0]]
```
发现骨骼正常，但似乎动作就不正确了。
![image](https://user-images.githubusercontent.com/20351890/71167331-75c90f00-228f-11ea-82a3-44d58e6e5967.png)
若改变了initial_directions，需要再更改什么才能使动作正常呢？

**Comment by KevinLTT** [comment]
bvh文件中记录的骨骼旋转角度都是相对于初始pose而言的，修改了initial_directions后相当于修改了初始pose，因此动作会出现异常。
你可以尝试下把[pose2euler](https://github.com/KevinLTT/video2bvh/blob/3948283164cbc190ae8cfca1abb054cd058b230e/bvh_skeleton/cmu_skeleton.py#L184)方法中的x_dir，y_dir，z_dir替换为y_dir，z_dir，x_dir试试。

**Comment by wtnan2003** [comment]
@KevinLTT 特别感谢您能回复，但是如果仅仅将此处：
https://github.com/KevinLTT/video2bvh/blob/3948283164cbc190ae8cfca1abb054cd058b230e/bvh_skeleton/cmu_skeleton.py#L254
x_dir，y_dir，z_dir替换为y_dir，z_dir，x_dir，会导致错误:
![image](https://user-images.githubusercontent.com/20351890/71332490-5a048800-2571-11ea-8e8d-dafe432ac41b.png)

`File "/home/nd/pose_demo_server/video2bvh-master/try.py", line 20, in <module> 
       channels, header = bip_skel.poses2bvh(pose3d_world, output_file=bvh_file)`

`File "/home/nd/pose_demo_server/video2bvh-master/bvh_skeleton/bip_skeleton.py", line 285, in poses2bvh
   channels.append(self.pose2euler(pose, header))`

  `File "/home/nd/pose_demo_server/video2bvh-master/bvh_skeleton/bip_skeleton.py", line 254, in pose2euler
    dcm = math3d.dcm_from_axis(y_dir, z_dir, x_dir, order)`

  `File "/home/nd/pose_demo_server/video2bvh-master/bvh_skeleton/math3d.py", line 34, in dcm_from_axis
    axis[name[(idx1 + 1) % 3]], axis[name[(idx1 + 2) % 3]]`

 ` File "<__array_function__ internals>", line 6, in cross`

 ` File "/home/nd/anaconda3/envs/stylegan/lib/python3.6/site-packages/numpy/core/numeric.py", line 1537, in cross
    axisb = normalize_axis_index(axisb, b.ndim, msg_prefix='axisb')
numpy.AxisError: axisb: axis -1 is out of bounds for array of dimension 0`

似乎需要更改order？关节的order是如何确定的呢？

https://github.com/KevinLTT/video2bvh/blob/3948283164cbc190ae8cfca1abb054cd058b230e/bvh_skeleton/cmu_skeleton.py#L203

**Comment by KevinLTT** [comment]
以Hips为例
```python
if joint == 'Hips':
    x_dir = pose[index['LeftUpLeg']] - pose[index['RightUpLeg']]
    y_dir = None
    z_dir = pose[index['Spine']] - pose[joint_idx]
    order = 'zyx'
```
在初始姿态中，从LeftUpLeg到RightUpLeg的向量与x轴平行，从Hips到Spine的向量与z轴平行，
这两个向量以及它们叉乘的向量所组成的标架与坐标系的标架是相同的。
而在估计得到的姿态中，由于关节旋转了，上述提到的两个向量的方向发生了变化，此时它们所组成的标架与原标架之间的变换矩阵即为关节的旋转矩阵。
这里的order是确定新标架的计算顺序，'zyx‘先以z_dir确定z轴方向，然后利用z_dir与x_dir之间的叉乘确定y轴方向，最后用z轴方向和y轴方向之间的叉乘确定x轴方向。

如果将初始姿态坐标顺序从xyz改为yzx，相当于对初始姿态进行了旋转，LeftUpLeg->RightUpLeg向量此时应该是和y轴平行，Hips->Spine向量此时是和x轴平行，所以代码应该改为
```python
if joint == 'Hips':
    x_dir = pose[index['Spine']] - pose[joint_idx]
    y_dir = pose[index['LeftUpLeg']] - pose[index['RightUpLeg']]
    z_dir = None
    order = 'xzy'
```
也就是我之前说的将x_dir，y_dir，z_dir替换为y_dir，z_dir，x_dir，order也做相应的变换即可。
后面的`dcm = math3d.dcm_from_axis(x_dir, y_dir, z_dir, order)`无需改动。

**Comment by wtnan2003** [comment]
感谢大佬这么详细回复！
按照之前所说尝试更改了各个关节的顺序：
1.原order是'zyx'的改为‘xzy’，如“Hips”改为：
```python
if joint == 'Hips':
    x_dir = pose[index['Spine']] - pose[joint_idx]
    y_dir = pose[index['LeftUpLeg']] - pose[index['RightUpLeg']]
    z_dir = None
    order = 'xzy'
```
2.原order是'zxy'的改为‘xyz’，如“Neck1”改为：
```python
   elif joint == 'Neck1':
       y_dir = None
       z_dir = pose[index['Spine1']] - pose[joint_idx]
       x_dir = pose[index['HeadEndSite']] - pose[index['Spine1']]
       order = 'xyz'
```
3.原order是'xzy'的改为‘yxz’，如“LeftArm”改为：
```python
elif joint == 'LeftArm':
    y_dir = pose[index['LeftForeArm']] - pose[joint_idx]
    z_dir = pose[index['LeftForeArm']] - pose[index['LeftHand']]
    x_dir = None
    order = 'yxz'
```
没有报错，但动作仍然不正确，有可能其他什么地方需要修改？
![Learnable Triangulation of Human Pose20191223_165132](https://user-images.githubusercontent.com/20351890/71347176-addc9480-25a4-11ea-8fe9-71d963879d98.gif)

**Comment by KevinLTT** [comment]
将bvh中的旋转顺序调整为‘xyz'就正常了
[cxk_yzx.bvh.txt](https://github.com/KevinLTT/video2bvh/files/3997096/cxk_yzx.bvh.txt)

**Comment by wtnan2003** [comment]
已经现在导入3dsmax已经能够看清大致动作了，不过貌似盆骨方向有点问题，竟然跟身体垂直。。我找找原因
![Learnable Triangulation of Human Pose20191224_151311](https://user-images.githubusercontent.com/20351890/71400481-ec845480-2661-11ea-97b5-9afcb9728ef5.gif)

**Comment by KevinLTT** [comment]
我在blender中显示是正常的，可能是3dsmax里某些设置的原因

**Comment by wtnan2003** [comment]
@KevinLTT bvh_skeleton module 里面有挺多看不懂的地方，我感觉是我的一些基本概念缺失，比如欧拉角计算、还有你前面提到的“确定新标架”我就不太理解，请问有没有什么参考阅读文档呢？感觉这个工作挺有价值的

**Comment by KevinLTT** [comment]
《3D数学基础：图形与游戏开发》，可以看看这本书

**Comment by Kismetzc** [comment]
@wtnan2003 您好呀，请问您最后成功了吗

**Comment by 2265865006** [comment]
太强了，感谢各位大佬详细的分享

**Comment by 2265865006** [comment]
@wtnan2003 @Kismetzc 关于最后3dsmax里骨盆方向错误的问题想问一下你们找到原因所在了吗，可以给一些指导吗，多谢啦

**Comment by 2265865006** [comment]
呕吼，我找到原因了，查阅了官方文档，我发现事实上我们要转换的initial_directions并不是y z x ，而是x z y（后续的修改需要做出对应的调整），这样我得到的骨盆是正确的旋转。
