### ISSUE TITLE
How can I set cam_id and subject for different videos?

### ISSUE THREAD

**Issue by hellozjj** [KevinLTT/video2bvh#5]
How can I set cam_id and subject for different videos?
And the cameras.h5 can stay same for different videos or I need to set?

**Comment by KevinLTT** [comment]
As the estimated 3D pose is in camera coordinate, the human orientation is up side down if we directly visualizing it.  The camera parameters is only used for better visualization, so you can keep the default settings for all videos.

**Comment by hellozjj** [comment]
> As the estimated 3D pose is in camera coordinate, the human orientation is up side down if we directly visualizing it. The camera parameters is only used for better visualization, so you can keep the default settings for all videos.

Thanks. And the root joint are not moving in the visuaization?

**Comment by KevinLTT** [comment]
Yes. The root joint is the coordinate origin.

**Comment by hellozjj** [comment]
> Yes. The root joint is the coordinate origin.

Is there any way can we estimate the root joint position to let root joint moves too?

**Comment by hellozjj** [comment]
> Yes. The root joint is the coordinate origin.

I have another question, hoping you can help to solve. Thanks very much.
Is the output 'pose3d_world' the world position of every joint at every frame?
If so,  what the unit of the 'pose3d_world' is? Is it 'm(eter)'?
Thanks again.

**Comment by KevinLTT** [comment]
> Is there any way can we estimate the root joint position to let root joint moves too?

You can see the original paper of video pose https://arxiv.org/abs/1811.11742. In their semi-supervised training, they proposed a trajectory model to estimatie the global position.

> I have another question, hoping you can help to solve. Thanks very much.
> Is the output 'pose3d_world' the world position of every joint at every frame?
> If so, what the unit of the 'pose3d_world' is? Is it 'm(eter)'?
> Thanks again.

Maybe 'poe3d_world' is not a proper name, because in fact we can't get the global position of the root joint. The joint positions are offset relative to the root joint. 
The unit is mm.

**Comment by hellozjj** [comment]
You can see the original paper of video pose https://arxiv.org/abs/1811.11742. In their semi-supervised training, they proposed a trajectory model to estimatie the global position.



so if I run the original paper's code, can I get the root position? I see in one case(ice case), the root joint is not moving either.

**Comment by KevinLTT** [comment]
I have not tired their trajectory model.You can check their project https://github.com/facebookresearch/VideoPose3D.

**Comment by hellozjj** [comment]
> I have not tired their trajectory model.You can check their project https://github.com/facebookresearch/VideoPose3D.
@KevinLTT  Thanks very much! 
Can I ask another question? Thanks! 
I want to know the height of person in a jpeg, and I get the 2D keypoints pose using your openpose code. I calculate the difference between the head and the foot. But I don't know what's the unit of 2D keypoint. Is it mm or pixel?

**Comment by KevinLTT** [comment]
For 2D keypoint, the unit is pixel. If you want to estimate person height, I think you should calculate the distance in 3D space.

**Comment by hellozjj** [comment]
> For 2D keypoint, the unit is pixel. If you want to estimate person height, I think you should calculate the distance in 3D space.

Thanks very much!

**Comment by starlesschan** [comment]
> > For 2D keypoint, the unit is pixel. If you want to estimate person height, I think you should calculate the distance in 3D space.
> 
> Thanks very much!

hello, have you solved the problem? the problem about "estimate the root joint position to let root joint move"

**Comment by starlesschan** [comment]
> > > For 2D keypoint, the unit is pixel. If you want to estimate person height, I think you should calculate the distance in 3D space.
> > 
> > 
> > Thanks very much!
> 
> hello, have you solved this problem? the problem  "estimate the root joint position to let root joint move"

**Comment by starlesschan** [comment]
@hellozjj hello, have you solved the problem? the problem about how to  estimate the root joint position to let root joint moves
