### ISSUE TITLE
How I can retarget the motion to other 3D character model?

### ISSUE THREAD

**Issue by Gorosia** [KevinLTT/video2bvh#6]
Thanks for your work!
I followed your 'demo.ipynb' and made my own bvh file. 
But it seems not work well, even if I use your 'cvh.bvh' file.

I downloaded blender, MakeHuman, makewalk.

First i load my mhx2 file (I use 'cmu mb skeleton)
![스크린샷 2020-04-10 오전 11 01 37](https://user-images.githubusercontent.com/33584055/78955645-d1f3bf80-7b1a-11ea-9d37-d1df56c25e18.png)

And 'load and retarget' your 'cvh.bvh'
![스크린샷 2020-04-10 오전 11 01 57](https://user-images.githubusercontent.com/33584055/78955684-efc12480-7b1a-11ea-8c2e-2f93c33e4ddc.png)

and play...
![스크린샷 2020-04-10 오전 10 57 32](https://user-images.githubusercontent.com/33584055/78956053-13389f00-7b1c-11ea-982a-de733c6410c7.png)
(sorry I can't make gif file or video file)

How do I fix this error?

**Comment by KevinLTT** [comment]
See this issue #3. Modify 'readBvhFile' function in makehuman may help.

**Comment by Gorosia** [comment]
Thanks for your comment. How about specifying this issue 'README.md' or somewhere?
