### ISSUE TITLE
Problem with module

### ISSUE THREAD

**Issue by ideo65** [KevinLTT/video2bvh#7]
Hi
I have a problem using video2bvh, when I try to run demo.ipynb I have this error in the first cell :

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-63597de30233> in <module>
----> 1 from pose_estimator_2d import openpose_estimator
      2 from pose_estimator_3d import estimator_3d
      3 from utils import smooth, vis, camera
      4 from bvh_skeleton import openpose_skeleton, h36m_skeleton, cmu_skeleton
      5 
~/video2bvh/pose_estimator_2d/openpose_estimator.py in <module>
      1 from .estimator_2d import Estimator2D
----> 2 from openpose import pyopenpose as op
      3 
      4 
      5 class OpenPoseEstimator(Estimator2D):
ModuleNotFoundError: No module named 'openpose'

But Openpose is installed and working, I think I forget to do something, do I have to specify where is located my Openpose folder ?
Thanks for your work

**Comment by ideo65** [comment]
Hi,
I still have difficulties to make video2bvh works as I mentionned above, if anyone can help me, it would be great, I'm not expert with Jupyter Notebook
Thanks again !

**Comment by KevinLTT** [comment]
Sorry, I've never encountered this problem before. Maybe you can ask [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) for help.

**Comment by ideo65** [comment]
Thank you for answering my question, I'll ask them but I'm not sure they can help me about a project they didn't create like video2bvh
But can you just tell me if my structure should be able to work (see the screenshot), both folders "openpose" and "video2bvh" are in the root when I launch Jupyter Notebook

![screen](https://user-images.githubusercontent.com/52700001/80275636-d91af000-870c-11ea-85a1-3285b1ac57c0.jpg)

**Comment by KevinLTT** [comment]
Did you install the openpose python module?

**Comment by ideo65** [comment]
Yes, I think that's my problem, I can't see this module, I try to install it but I'm facing issues
thanks for your answer

**Comment by ideo65** [comment]
I think the problem is because I'm on Mac OS, and the path to this module is not the same (on MAc OS /usr/local/python), but I don't see where I can modify it in your file.

**Comment by KevinLTT** [comment]
See https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#python-api for help. 
The only thing you need to specify in this project about OpenPose is the OpenPose model folder path.
`e2d = openpose_estimator.OpenPoseEstimator(model_folder='/openpose/models/')`

**Comment by ideo65** [comment]
I finally solved my problem by adding these lines in the file pose_estimator_2d.py :
`import sys
sys.path.append('/usr/local/python');`
Maybe it can help some MacOs users

Now I have a problem with Pytorch installation (during "Estimate 3D pose from 2D pose" step):
---> 47         raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I think I need to re-install it
